name: Docker Image Build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # https://docs.github.com/de/packages/learn-github-packages/about-permissions-for-github-packages#about-scopes-and-permissions-for-package-registries
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .docker-config/webserver/Dockerfile
          push: true
          tags: user/app:latest

      # TODO: store as artifact?

    # TODO: trigger dokku
    # https://github.com/dokku/github-action/blob/master/example-workflows/build-and-deploy.yml
    # - name: Push to dokku
    #     uses: dokku/github-action@master
    #     with:
    #       git_remote_url: 'ssh://dokku@dokku.me:22/appname'
    #       ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       deploy_docker_image: ${{ github.repository }}:${{ github.sha }}